sudo: false
language: go
go:
- 1.8
- tip

install:
- go get github.com/golang/dep/cmd/dep
- dep ensure

script:
- go test
- go build -i -o goose ./cmd/goose
- ./goose -dir=example/migrations sqlite3 sql.db up
- ./goose -dir=example/migrations sqlite3 sql.db version
- ./goose -dir=example/migrations sqlite3 sql.db down
- ./goose -dir=example/migrations sqlite3 sql.db status
- go build -i -o custom-goose ./example/migrations-go
- ./custom-goose -dir=example/migrations-go sqlite3 go.db up
- ./custom-goose -dir=example/migrations-go sqlite3 go.db version
- ./custom-goose -dir=example/migrations-go sqlite3 go.db down
- ./custom-goose -dir=example/migrations-go sqlite3 go.db status
